# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               "EFT-TBT Groups"
email:               eft.tbt@gmail.com
tagline:             "Isabelle Levrat"
description:         "Isabelle Levrat<br />EFT–TBT Groups"
# url:                 "http://eft-tbt.com"
url:                 "http://efttbthub.github.io"
baseurl:             "/eft-tbt-v1-test"


exclude: ["CNAME", "README.md", "LICENSE.md"]

gems: [jekyll-paginate]
paginate:            5

kramdown:
  input: GFM

